# Generated by Django 4.2.7 on 2025-11-21 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('MarketID', models.AutoField(primary_key=True, serialize=False)),
                ('MarketName', models.CharField(max_length=100)),
                ('Province', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=100)),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('PriceID', models.AutoField(primary_key=True, serialize=False)),
                ('Price', models.IntegerField()),
                ('PriceDate', models.DateField()),
                ('Market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.market')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
            options={
                'unique_together': {('Product', 'Market', 'PriceDate')},
            },
        ),
    ]
